spring:
  metrics:
    export:
      enabled: true
      send-latest: true
      delay-millis: 1000
      statsd:
        host: 192.168.99.100
        port: 8125
        prefix: kafka-example
      kafka:
        enabled: true
#        consumer-groups: demo1,demo2